"""
Plot calibration to Nigeria.

Two modes:
  python plot_figS2_calibration.py --run-sim   # run calibration + extract CSVs (VM)
  python plot_figS2_calibration.py             # plot from saved CSVs (local)
"""
import argparse

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sciris as sc
import seaborn as sns

import run_calibration as rc
import utils as ut


def save_figS2_data(calib, res_to_plot=100, resfolder='results'):
    """Re-run the top-N Optuna trials by objective, extract the same
    series the v2 script produced, and write CSVs for the plotter.

    v3 dropped calib.analyzer_results / calib.sim_results / calib.target_data,
    so figS2 uncertainty bands are regenerated by re-running the top trials
    rather than reading cached calibration results."""
    import sciris as sc
    import hpvsim as hpv

    # Sort trials by objective (ascending — best first); skip failed trials.
    trials = sorted(
        (t for t in calib.study.trials if t.value is not None),
        key=lambda t: t.value,
    )
    n = min(res_to_plot, len(trials))

    # Re-run the top-N sims serially (process cap: 1 worker per session rules).
    sims = []
    for trial in trials[:n]:
        pars_spec = sc.dcp(calib.calib_pars)
        for parname, spec in pars_spec.items():
            if parname in trial.params:
                spec['value'] = trial.params[parname]
        s = calib.build_fn(sc.dcp(calib.sim), calib_pars=pars_spec)
        s.run()
        sims.append(s)

    # Cancers-by-age at 2020: by_age analyzer is already on each sim (from
    # calib.sim); to_dataframe returns year-indexed, age-bin-column DataFrame.
    # Bin index 0..N-1 matches the v2 CSV 'bin' column that plot_calib reads.
    per_trial = np.array([
        s.analyzers['all_hpv_by_age'].to_dataframe('cancers').iloc[0].values
        for s in sims
    ])
    pd.DataFrame({
        'bin': np.arange(per_trial.shape[1]),
        'median': np.median(per_trial, axis=0),
        'pi95_low': np.percentile(per_trial, 2.5, axis=0),
        'pi95_high': np.percentile(per_trial, 97.5, axis=0),
    }).to_csv(f'{resfolder}/figS2_cancers_by_age.csv', index=False)

    # Genotype distributions: results_by_genotype returns year-indexed DataFrame
    # with genotype columns (hpv16, hpv18, hi5, ohr), normalize=True gives
    # row-level distributions. Extract 2015 row for each sim.
    # cum_cins was not ported to v3; use n_cin (prevalent CIN count) as the
    # CIN genotype distribution proxy — same denominator as v2 cin_genotype_dist.
    for rbg_key, rkey in (('cum_cancers', 'cancerous_genotype_dist'),
                          ('n_cin', 'cin_genotype_dist')):
        per_trial = np.array([
            hpv.results_by_genotype(s, key=rbg_key, normalize=True).loc[2015.0].values
            for s in sims
        ])
        rows = []
        for bi in range(per_trial.shape[1]):
            arr = per_trial[:, bi]
            q1, med, q3 = np.percentile(arr, [25, 50, 75])
            iqr = q3 - q1
            lo_cand = arr[arr >= q1 - 1.5 * iqr]
            hi_cand = arr[arr <= q3 + 1.5 * iqr]
            rows.append({
                'bin': bi,
                'q1': float(q1), 'med': float(med), 'q3': float(q3),
                'whislo': float(lo_cand.min()) if lo_cand.size else float(q1),
                'whishi': float(hi_cand.max()) if hi_cand.size else float(q3),
            })
        pd.DataFrame(rows).to_csv(f'{resfolder}/figS2_{rkey}.csv', index=False)

    # Target CSVs — copy the source data files directly.
    # Use __file__-relative paths so the function works regardless of cwd.
    from pathlib import Path
    data_dir = Path(__file__).parent / 'data'
    for name, path in (('cancers',             data_dir / 'nigeria_cancer_cases.csv'),
                       ('cin_genotype',        data_dir / 'nigeria_cin_types.csv'),
                       ('cancerous_genotype',  data_dir / 'nigeria_cancer_types.csv')):
        pd.read_csv(path).to_csv(f'{resfolder}/figS2_target_{name}.csv', index=False)


def plot_calib(resfolder='results', outpath='figures/figS2_calibration.png'):
    ut.set_font(size=24)
    fig = plt.figure(layout='tight', figsize=(12, 11))
    canc_col = '#c1981d'
    ms = 80
    gen_cols = sc.gridcolors(4)

    gs0 = fig.add_gridspec(2, 1)
    gs00 = gs0[0].subgridspec(1, 1)
    gs01 = gs0[1].subgridspec(1, 2)

    # Panel A: Cancers by age, 2020
    cancers_df = pd.read_csv(f'{resfolder}/figS2_cancers_by_age.csv')
    target_cancers = pd.read_csv(f'{resfolder}/figS2_target_cancers.csv')
    age_labels = ['0', '15', '20', '25', '30', '35', '40', '45', '50', '55', '60', '65', '70', '75', '80', '85']
    x = np.arange(len(age_labels))

    ax = fig.add_subplot(gs00[0])
    cancers_df = cancers_df.sort_values('bin')
    ax.plot(cancers_df['bin'], cancers_df['median'], color=canc_col)
    ax.fill_between(cancers_df['bin'], cancers_df['pi95_low'],
                    cancers_df['pi95_high'], color=canc_col, alpha=0.3)
    ax.scatter(x, target_cancers['value'].values, marker='d', s=ms, color='k')
    ax.set_ylim([0, 2_500])
    ax.set_xticks(x, age_labels)
    sc.SIticks(ax)
    ax.set_xlabel('Age')
    ax.set_title('Cancers by age, 2020')

    # Panels B, C: CIN + cancer by genotype
    for ai, (rkey, target_name, rlabel) in enumerate([
        ('cin_genotype_dist', 'cin_genotype', 'HSILs'),
        ('cancerous_genotype_dist', 'cancerous_genotype', 'Cancers'),
    ]):
        ax = fig.add_subplot(gs01[ai])
        model_df = pd.read_csv(f'{resfolder}/figS2_{rkey}.csv')
        target_df = pd.read_csv(f'{resfolder}/figS2_target_{target_name}.csv')

        model_df = model_df.sort_values('bin')
        bxp_stats = [dict(med=r.med, q1=r.q1, q3=r.q3,
                          whislo=r.whislo, whishi=r.whishi, fliers=[],
                          label=str(int(r.bin))) for _, r in model_df.iterrows()]
        bp = ax.bxp(bxp_stats, positions=model_df['bin'].values,
                    patch_artist=True, showfliers=False, manage_ticks=False)
        for patch, color in zip(bp['boxes'], gen_cols):
            patch.set_facecolor(color)
        ax.scatter(np.arange(len(target_df)), target_df['value'].values, color='k', marker='d', s=ms)
        ax.set_ylim([0, 1])
        ax.set_xticks(np.arange(4), ['16', '18', 'Hi5', 'OHR'])
        ax.set_title(rlabel)

    fig.tight_layout()
    plt.savefig(outpath, dpi=300)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--run-sim', action='store_true',
                        help='Run calibration and save CSVs (heavy, VM-side)')
    # NOTE: v2.3.0_baseline has no figS2 CSVs. This default becomes fully
    # valid after the v3 freeze commit populates results/v3.0.0_baseline/.
    parser.add_argument('--resfolder', default='results/v2.3.0_baseline',
                        help='Dir with plot-ready CSVs (for plot mode only)')
    parser.add_argument('--outpath', default='figures/figS2_calibration.png')
    parser.add_argument('--res-to-plot', type=int, default=100)
    args = parser.parse_args()

    if args.run_sim:
        calib = rc.run_calib(n_trials=rc.n_trials, n_workers=rc.n_workers,
                             do_save=True, filestem='')
        save_figS2_data(calib, res_to_plot=args.res_to_plot, resfolder='results')
        print('Saved figS2 CSVs to results/ (copy to a versioned baseline dir to commit)')
    else:
        plot_calib(resfolder=args.resfolder, outpath=args.outpath)
        print('Done.')
